# CASA script to flag files with no calibration solutions in the database
# Automatically generated by caldb2aol.py script for formatting DB-calibration data -> AO-cal format
# Should be automatically executed by script caldb2aol.sh# The target_obsid = 1215080360 , calid = 1215119872
flagdata(vis='1215080360.ms',antenna='22')  # tileid = 107
flagdata(vis='1215080360.ms',antenna='31')  # tileid = 118
flagdata(vis='1215080360.ms',antenna='32')  # tileid = 121
flagdata(vis='1215080360.ms',antenna='45')  # tileid = 136
flagdata(vis='1215080360.ms',antenna='63')  # tileid = 158
flagdata(vis='1215080360.ms',antenna='64')  # tileid = 161
flagdata(vis='1215080360.ms',antenna='78')  # tileid = 2007
flagdata(vis='1215080360.ms',antenna='79')  # tileid = 2008
flagdata(vis='1215080360.ms',antenna='80')  # tileid = 2009
flagdata(vis='1215080360.ms',antenna='81')  # tileid = 2010
flagdata(vis='1215080360.ms',antenna='108')  # tileid = 2037
flagdata(vis='1215080360.ms',antenna='112')  # tileid = 2041
flagdata(vis='1215080360.ms',antenna='113')  # tileid = 2042
flagdata(vis='1215080360.ms',antenna='114')  # tileid = 2043
flagdata(vis='1215080360.ms',antenna='115')  # tileid = 2044
flagdata(vis='1215080360.ms',antenna='117')  # tileid = 2046
flagdata(vis='1215080360.ms',antenna='118')  # tileid = 2047
flagdata(vis='1215080360.ms',antenna='119')  # tileid = 2048
flagdata(vis='1215080360.ms',antenna='120')  # tileid = 2049
flagdata(vis='1215080360.ms',antenna='122')  # tileid = 2051
flagdata(vis='1215080360.ms',antenna='123')  # tileid = 2052
flagdata(vis='1215080360.ms',antenna='125')  # tileid = 2054
flagdata(vis='1215080360.ms',antenna='126')  # tileid = 2055
