#!/bin/bash

export OBSERVATION_ID=1342107776 
export TIME_RESOLUTION="1s"

N_SECONDS=1
N_SECONDS_PER_BATCH=1
# Set Observation ID and GPS second to process
START_GPSTIME=1342107784
LAST_GPSTIME=$(expr $START_GPSTIME + $N_SECONDS - 1 )
while ((START_GPSTIME <= LAST_GPSTIME ));
do 
END_GPSTIME=$((START_GPSTIME + N_SECONDS_PER_BATCH - 1))
if [ $END_GPSTIME -gt $LAST_GPSTIME ]; then
END_GPSTIME=$LAST_GPSTIME
fi
export START_GPSTIME
export END_GPSTIME
sbatch --export=ALL ./image_one_second.sh
START_GPSTIME=$((START_GPSTIME + N_SECONDS_PER_BATCH))
done
